users:
  ananos:
    name: Anastassios Nanos
    email: ananos@nubificus.co.uk
  cmainas:
    name: Charalampos Mainas
    email: cmainas@nubificus.co.uk
  gntouts:
    name: Georgios Ntoutsos
    email: gntouts@nubificus.co.uk
  johnp41:
    name: Ioannis Plakas
    email: iplakas@nubificus.co.uk
  mgkeka-nbfc:
    name: Maria Gkeka
    email: mgkeka@nubificus.co.uk
  panosmaurikos:
    name: Panagiotis Mavrikos
    email: pmavrikos@nubificus.co.uk
  zyfy29:
    name: zyfy29
    email: wasuremono127@gmail.com
  DionisiaK4:
    name: Dionisia Koronellou
    email: koronelloudionisia@gmail.com
  codesmith25103:
    name: sankalp
    email: sankalp25103@gmail.com
  vliaskov:
    name: Vasilis Liaskovitis
    email: vliaskovitis@suse.com
  amallikopoulou:
    name: Anastasia Mallikopoulou
    email: amallik@nubificus.co.uk
  copilot-pull-request-reviewerbot:
    name: copilot[bot]
    email: copilot[bot]@users.noreply.github.com
  dependabotbot:
    name: dependabot[bot]
    email: support@github.com
  KhitemMed:
    name: Medfouni Khitem
    email: lk_medfouni@esi.dz
  IrvingMg:
    name: Irving Mondragón
    email: mirvingr@gmail.com
  sidneychang:
    name: Xuedong Zhang
    email: 2190206983@qq.com
  spline2hg:
    name: spline2hg
    email: 181270613+spline2hg@users.noreply.github.com
  ishaanxgupta:
    name: Ishaan Gupta
    email: ishaankone@gmail.com
  hemang1404:
    name: Hemang Sharrma
    email: hemangsharrma@gmail.com
  ilp-sys:
    name: Jiwoo Ahn
    email: ikwydls1314@gmail.com
  goyalpalak18:
    name: Palak Goyal
    email: goyalpalak1806@gmail.com
  AyushSriv06:
    name: Ayush Srivastava
    email: ayushsrisks@gmail.com
  vinayakjeet:
    name: vinayakjeet
    email: vinayakjeetog@gmail.com
  Mysterio-17:
    name: Mradul Tiwari
    email: mradultiwari1708@gmail.com
  0xull:
    name: Ikeh Akinyemi
    email: mrikehchukwuka@gmail.com
